/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2021-11-19 10:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class impressum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tags/header.tag", Long.valueOf(1637317857247L));
    _jspx_dependants.put("/WEB-INF/tags/scripts.tag", Long.valueOf(1637318037881L));
    _jspx_dependants.put("/WEB-INF/tags/logoGSO.tag", Long.valueOf(1637317857247L));
    _jspx_dependants.put("/WEB-INF/tags/navigationbar.tag", Long.valueOf(1637318037881L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Impressum</title>\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_tag_005fnavigationbar_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<h2 class=\"text-center\" id=\"titleSite\">Impressum</h2>\r\n");
      out.write("\t<div style=\"padding-left:2%; padding-right:2%;\">\r\n");
      out.write("\t\t<article id=\"post-2383\" class=\"post-2383 page type-page status-publish hentry entry\">\r\n");
      out.write("\t\t<div class=\"entry-content\"><div class=\"entry-content-inner\">\r\n");
      out.write("\t\t<h2>Betreiber der Seite</h2>\t\t\r\n");
      out.write("\t\t<h3><strong>Schulleitung:</strong></h3>\t\t\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tOStD Bertram Wolf, Schulleiter<br>N.N, stellvertretender Schulleiter\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tGeorg-Simon-Ohm-Berufskolleg der Stadt Köln<br>Westerwaldstraße 92<br>51105 Köln<br>Tel.: 0221-8391320<br>Fax: 0221-8391328<br>Email:&nbsp;<a href=\"mailto:buero@gso-koeln.de\">buero@gso-koeln.de</a>\r\n");
      out.write("\t\t</p>\t\t\r\n");
      out.write("\t\t<h3>Schulträger (Diensteanbieter im Sinne des RStV/TMG):</h3>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tStadt Köln&nbsp;- Amt für Schulentwicklung\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tvertreten durch:&nbsp;<em>Oberbürgermeisterin Henriette Reker</em>\r\n");
      out.write("\t\t</p>\t\t\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tWilly-Brandt-Platz 3<br>\r\n");
      out.write("\t\t\t50679 Köln<br>\r\n");
      out.write("\t\t\tTelefon: (0221) 221-29204<br>\r\n");
      out.write("\t\t\tTelefax: (0221) 221-29240<br>\r\n");
      out.write("\t\t\tEmail:&nbsp;<a href=\"mailto:schulentwicklungsamt@stadt-koeln.de\">schulentwicklungsamt@stadt-koeln.de</a>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h3>Inhaltliche Verantwortung nach § 55 Abs. 2 RStV:</h3>\r\n");
      out.write("\t\t<p>OStD Bertram Wolf</p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t<h2>Rechtliche Hinweise</h2>\t\t\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t1. Haftungsbeschränkung<br>Die Inhalte dieser Website werden mit größtmöglicher Sorgfalt erstellt. \r\n");
      out.write("\t\t\tDer Anbieter übernimmt jedoch keine Gewähr für die Richtigkeit, Vollständigkeit und Aktualität der bereitgestellten Inhalte. \r\n");
      out.write("\t\t\tDie Nutzung der Inhalte der Website erfolgt auf eigene Gefahr des Nutzers. \r\n");
      out.write("\t\t\tNamentlich gekennzeichnete Beiträge geben die Meinung des jeweiligen Autors und nicht immer die Meinung des Anbieters wieder. \r\n");
      out.write("\t\t\tMit der reinen Nutzung der Website des Anbieters kommt keinerlei Vertragsverhältnis zwischen dem Nutzer und dem Anbieter zustande.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t2. Externe Links<br>\r\n");
      out.write("\t\t\tDiese Website enthält Verknüpfungen zu Websites Dritter (\"externe Links\"). \r\n");
      out.write("\t\t\tDiese Websites unterliegen der Haftung der jeweiligen Betreiber. \r\n");
      out.write("\t\t\tDer Anbieter hat bei der erstmaligen Verknüpfung der externen Links die fremden Inhalte daraufhin überprüft, ob etwaige Rechtsverstöße bestehen. \r\n");
      out.write("\t\t\tZu dem Zeitpunkt waren keine Rechtsverstöße ersichtlich. \r\n");
      out.write("\t\t\tDer Anbieter hat keinerlei Einfluss auf die aktuelle und zukünftige Gestaltung und auf die Inhalte der verknüpften Seiten. \r\n");
      out.write("\t\t\tDas Setzen von externen Links bedeutet nicht, dass sich der Anbieter die hinter dem Verweis oder Link liegenden Inhalte zu Eigen macht. \r\n");
      out.write("\t\t\tEine ständige Kontrolle dieser externen Links ist für den Anbieter ohne konkrete Hinweise auf Rechtsverstöße nicht zumutbar. \r\n");
      out.write("\t\t\tBei Kenntnis von Rechtsverstößen werden jedoch derartige externe Links unverzüglich gelöscht.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t3. Urheber- und Leistungsschutzrechte<br>\r\n");
      out.write("\t\t\tDie auf dieser Website veröffentlichten Inhalte unterliegen dem deutschen Urheber- und Leistungsschutzrecht. \r\n");
      out.write("\t\t\tJede vom deutschen Urheber- und Leistungsschutzrecht nicht zugelassene Verwertung bedarf der vorherigen schriftlichen Zustimmung des Anbieters oder jeweiligen Rechteinhabers. \r\n");
      out.write("\t\t\tDies gilt insbesondere für Vervielfältigung, Bearbeitung, Übersetzung, Einspeicherung, Verarbeitung bzw. Wiedergabe von Inhalten in Datenbanken oder anderen elektronischen Medien und Systemen. \r\n");
      out.write("\t\t\tInhalte und Rechte Dritter sind dabei als solche gekennzeichnet. \r\n");
      out.write("\t\t\tDie unerlaubte Vervielfältigung oder Weitergabe einzelner Inhalte oder kompletter Seiten ist nicht gestattet und strafbar. \r\n");
      out.write("\t\t\tLediglich die Herstellung von Kopien und Downloads für den persönlichen, privaten und nicht kommerziellen Gebrauch ist erlaubt.<br>\r\n");
      out.write("\t\t\tDie Darstellung dieser Website in fremden Frames ist nur mit schriftlicher Erlaubnis zulässig.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t4. Datenschutz<br>\r\n");
      out.write("\t\t\tDurch den Besuch der Website des Anbieters können Informationen über den Zugriff (Datum, Uhrzeit, betrachtete Seite) gespeichert werden. \r\n");
      out.write("\t\t\tDiese Daten gehören nicht zu den personenbezogenen Daten, sondern sind anonymisiert. Sie werden ausschließlich zu statistischen Zwecken ausgewertet. \r\n");
      out.write("\t\t\tEine Weitergabe an Dritte, zu kommerziellen oder nichtkommerziellen Zwecken, findet nicht statt.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tDer Anbieter weist ausdrücklich darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen und nicht lückenlos vor dem Zugriff durch Dritte geschützt werden kann.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tDie Verwendung der Kontaktdaten des Impressums zur gewerblichen Werbung ist ausdrücklich nicht erwünscht, es sei denn der Anbieter hatte zuvor seine schriftliche Einwilligung erteilt oder es besteht bereits eine Geschäftsbeziehung. \r\n");
      out.write("\t\t\tDer Anbieter und alle auf dieser Website genannten Personen widersprechen hiermit jeder kommerziellen Verwendung und Weitergabe ihrer Daten.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\t5. Besondere Nutzungsbedingungen<br>\r\n");
      out.write("\t\t\tSoweit besondere Bedingungen für einzelne Nutzungen dieser Website von den vorgenannten Nummern 1. bis 4. abweichen, wird an entsprechender Stelle ausdrücklich darauf hingewiesen. \r\n");
      out.write("\t\t\tIn diesem Falle gelten im jeweiligen Einzelfall die besonderen Nutzungsbedingungen.\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t<p>\r\n");
      out.write("\t\t\tQuelle: www.Juraforum.de - Rechtportal mit Anwaltssuche\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</article>\r\n");
      out.write("\t</div>\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fscripts_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:header
    org.apache.jsp.tag.web.header_tag _jspx_th_tag_005fheader_005f0 = new org.apache.jsp.tag.web.header_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fheader_005f0);
    try {
      _jspx_th_tag_005fheader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fheader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fheader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fnavigationbar_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:navigationbar
    org.apache.jsp.tag.web.navigationbar_tag _jspx_th_tag_005fnavigationbar_005f0 = new org.apache.jsp.tag.web.navigationbar_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fnavigationbar_005f0);
    try {
      _jspx_th_tag_005fnavigationbar_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fnavigationbar_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fnavigationbar_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fscripts_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:scripts
    org.apache.jsp.tag.web.scripts_tag _jspx_th_tag_005fscripts_005f0 = new org.apache.jsp.tag.web.scripts_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fscripts_005f0);
    try {
      _jspx_th_tag_005fscripts_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fscripts_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fscripts_005f0);
    }
    return false;
  }
}
