/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.19
 * Generated at: 2021-11-19 10:44:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class info_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/tags/header.tag", Long.valueOf(1637317857247L));
    _jspx_dependants.put("/WEB-INF/tags/scripts.tag", Long.valueOf(1637318037881L));
    _jspx_dependants.put("/WEB-INF/tags/logoGSO.tag", Long.valueOf(1637317857247L));
    _jspx_dependants.put("/WEB-INF/tags/navigationbar.tag", Long.valueOf(1637318037881L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Informationen</title>\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fheader_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_tag_005fnavigationbar_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t<h2 class=\"text-center\" id=\"titleSite\">Schulpartnerschaft Köln-Warschau</h2>\r\n");
      out.write("    ");
      if (_jspx_meth_tag_005fscripts_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("    \t\t<div class=\"col\">\r\n");
      out.write("    \t\t\t<div class=\"text-info\">Wie kam die Partnerschaft zustande?</div>\r\n");
      out.write("    \t\t\t<p>\r\n");
      out.write("    \t\t\tIn den politischen Umwälzungen seit 1989 öffnete sich der \"eiserne Vorhang\", \r\n");
      out.write("    \t\t\tder Europa von Norden nach Süden trennte. \r\n");
      out.write("    \t\t\tIn dieser veränderten politischen Lage suchte eine Warschauer Kollegin, Jadwiga Smirnow, \r\n");
      out.write("    \t\t\tKontakt zu einer deutschen Schule und fand die Georg-Simon-Ohm- Schule. \r\n");
      out.write("    \t\t\tSeitdem besuchen wir uns jedes Jahr gegenseitig und organisieren so einen Austausch mit Schülerinnen und Schülern sowie Lehrerinnen und Lehrern.\r\n");
      out.write("    \t\t\t</p>    \t\t\t\r\n");
      out.write("    \t\t\t<p>\r\n");
      out.write("\t    \t\t\t<ul>\r\n");
      out.write("\t    \t\t\t\t<lh class=\"text-info\">Wie bereiten wir auf den Austausch vor?</lh>\r\n");
      out.write("\t    \t\t\t\t<li>Informationsveranstaltungen in unterschiedlichen Schulklassen und Bildungsgängen mit Präsentation von Bildern und Filmen vergangener Austausche</li>\r\n");
      out.write("\t    \t\t\t\t<li>Es findet immer ein Vorbereitungsseminar statt: Deutsch-polnische Geschichte und Beziehungen, Ethikcodex für die Gruppe, reisepraktische Fragen...</li>\r\n");
      out.write("\t    \t\t\t\t<li>Gemeinsame Programmgestaltung mit polnischer Seite</li>\r\n");
      out.write("\t    \t\t\t</ul>\r\n");
      out.write("    \t\t\t</p>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col\">\r\n");
      out.write("    \t\t\t<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/iW6LdbL6QNg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<hr>\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("    \t\t<div class=\"col\">\r\n");
      out.write("    \t\t\t<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/OSKXaWMZ5Yg\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col\">\r\n");
      out.write("    \t\t\t<ul>\r\n");
      out.write("    \t\t\t\t<lh class=\"text-info\">Welche Ziele streben wir an?</lh>\r\n");
      out.write("    \t\t\t\t<li>Aus ehemaligen Feinden werden Freunde</li>\r\n");
      out.write("    \t\t\t\t<li>Wir bauen nicht mehr zeitgemäße Vorurteile auf beiden Seiten ab und tragen vertrauensbildend zu einer neuen europäischen Partnerschaft bei</li>\r\n");
      out.write("    \t\t\t\t<li>Wir geben bilaterale Einblicke in das Verständnis von \"Land und Leuten\"</li>\r\n");
      out.write("    \t\t\t\t<li>Unterrichtsbesuche und Hospitationen an der Partnerschule</li>\r\n");
      out.write("    \t\t\t\t<li>Kontaktaufnahme mit polnischen Unternehmen zur Vermittlung von Schülerpraktika</li>\r\n");
      out.write("    \t\t\t\t<li>Wir eröffnen Begegnungsräume unter jungen Polen und Deutschen: Die jungen Menschen aus beiden Ländern organisieren wichtige Programmpunkte eigenverantwortlich</li>\r\n");
      out.write("    \t\t\t\t<li>Wir führen in die zwischenstaatlichen deutsch-polnischen Beziehungen ein</li>\r\n");
      out.write("    \t\t\t\t<li>Wir bringen Geschichte zur Sprache, weil wir die Überzeugung haben, dass wir nur so Anknüpfungen für das zukünftige Verhältnis junger Deutscher und Polen in Europa finden werden</li>    \t\t\t\r\n");
      out.write("    \t\t\t\t<li>Wir öffnen Wege, damit junge Menschen die gewonnenen Kontakte und Freundschaften erhalten und pflegen</li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<hr>\r\n");
      out.write("    \t<div class=\"row\" style=\"margin-bottom:2%;\">\r\n");
      out.write("    \t\t<div style=\"margin-left:auto; margin-right:auto;\">\r\n");
      out.write("    \t\t\t<iframe src=\"https://player.vimeo.com/video/20199219?h=e1fe7eb52f\" width=\"640\" height=\"360\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<div class=\"row\">\r\n");
      out.write("    \t\t<div class=\"col border-right\">\r\n");
      out.write("\t\t\t    <ul>\r\n");
      out.write("    \t\t\t\t<lh class=\"text-info\">Welche Erfolge hatten wir bisher?</lh>\r\n");
      out.write("    \t\t\t\t<li>Seit Beginn der Maßnahme ein deutlich freundschaftlicheres Verhältnis der Partner.</li>\r\n");
      out.write("    \t\t\t\t<li>Viele gegenseitige Kontakte, Begegnungen, und Besuche, die nach dem Schüleraustausch spontan und privat stattgefunden haben, darunter sogar eine Hochzeit.</li>\r\n");
      out.write("    \t\t\t\t<li>Wir sprechen mit Partnerbetrieben unserer Schule und kommunizieren bei Rückfragen, dass unsere Organisation nicht touristisch, sondern Völker verbindend wirkt, wobei wir bei bisherigen Kontakten immer positives Echos hatten.</li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t\t<div class=\"col\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("    \t\t\t\t<lh class=\"text-info\">Wer fördert diese Begegnungen ideell und finanziell?</lh>\r\n");
      out.write("    \t\t\t\t<li>Betriebe, indem sie durch die Freistellung von Auszubildenden einen Betrag zur Völkerverständigung zwischen Deutschland und Polen einbringen...</li>\r\n");
      out.write("    \t\t\t\t<li>Die Schulleitung durch Freistellung von zwei Lehrkräften während der Begegnungen...</li>\r\n");
      out.write("    \t\t\t\t<li>Die Schülervertretung, weil sie sie immer wieder auf die Wichtigkeit dieser Beziehungen hinweist, was in der Protokollen der SV  und Schulkonferenz nachgelesen werden kann...</li>\r\n");
      out.write("    \t\t\t\t<li>Das Deutsch-polnische Jugendwerk mit einer Förderung von jährlich ca. 5.000,00 EUR</li>\r\n");
      out.write("    \t\t\t\t<li>Der Förderverein des Berufskollegs mit einem Betrag von jährlich ca. 1.000,00 EUR</li>\r\n");
      out.write("    \t\t\t</ul>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t<hr>\r\n");
      out.write("    \t<h4 class=\"text-center\">Ansprechpartner</h4>\r\n");
      out.write("  \t    <div class=\"row\">\r\n");
      out.write("  \t    \t<div class=\"col\">\r\n");
      out.write("  \t    \t\t<h5><strong>Jörg Buschmann</strong>, Fachlehrer Wirtschaft/Politik</h5>\r\n");
      out.write("  \t    \t</div>\r\n");
      out.write("\t    \t<div class=\"col\">\r\n");
      out.write("  \t    \t\t<h5><strong>Volker Stern</strong>, Fachlehrer Deutsch/Politik</h5>\r\n");
      out.write("  \t    \t</div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tag_005fheader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:header
    org.apache.jsp.tag.web.header_tag _jspx_th_tag_005fheader_005f0 = new org.apache.jsp.tag.web.header_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fheader_005f0);
    try {
      _jspx_th_tag_005fheader_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fheader_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fheader_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fnavigationbar_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:navigationbar
    org.apache.jsp.tag.web.navigationbar_tag _jspx_th_tag_005fnavigationbar_005f0 = new org.apache.jsp.tag.web.navigationbar_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fnavigationbar_005f0);
    try {
      _jspx_th_tag_005fnavigationbar_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fnavigationbar_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fnavigationbar_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tag_005fscripts_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tag:scripts
    org.apache.jsp.tag.web.scripts_tag _jspx_th_tag_005fscripts_005f0 = new org.apache.jsp.tag.web.scripts_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tag_005fscripts_005f0);
    try {
      _jspx_th_tag_005fscripts_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tag_005fscripts_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tag_005fscripts_005f0);
    }
    return false;
  }
}
